name: cvec
version: 2.4
date: 14/09/2012
description: Compact vectors over finite fields

authors:
    - name: Max Neunhoeffer
      url: http://www-groups.mcs.st-and.ac.uk/~neunhoef/

maintainers:
    - name: Max Neunhoeffer
      url: http://www-groups.mcs.st-and.ac.uk/~neunhoef/

GAP: ">=4.5.5"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.2"
    - name: "IO"
      version: ">= 4.1"
    - name: "orb"
      version: ">= 4.2"

www: http://www-groups.mcs.st-and.ac.uk/~neunhoef/Computer/Software/Gap/cvec.html
readme: http://www-groups.mcs.st-and.ac.uk/~neunhoef/Computer/Software/Gap/cvec/README.cvec
packageinfo: http://www-groups.mcs.st-and.ac.uk/~neunhoef/Computer/Software/Gap/cvec/PackageInfo.g

downloads:
    - name: .tar.gz
      url: http://www-groups.mcs.st-and.ac.uk/~neunhoef/Computer/Software/Gap/cvec/cvec-2.4.tar.gz

abstract: This package provides an implementation of compact vectors over finite   fields. Contrary to earlier implementations no table lookups are used   but only word-based processor arithmetic. This allows for bigger finite   fields and higher speed.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
