name: cvec
version: 2.5
date: 31/04/2014
description: Compact vectors over finite fields

authors:
    - name: Max Neunhoeffer
      url: http://www-groups.mcs.st-and.ac.uk/~neunhoef/

GAP: ">=4.5.5"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.2"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "IO"
      version: ">= 4.1"
      url: "http://neunhoef.github.io/io/"
    - name: "orb"
      version: ">= 4.2"
      url: "http://neunhoef.github.io/orb/"

www: http://neunhoef.github.io/cvec/
readme: http://neunhoef.github.io/cvec/README
packageinfo: http://neunhoef.github.io/cvec/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/neunhoef/cvec/releases/download/v2.5/cvec-2.5.tar.gz
    - name: .tar.bz2
      url: https://github.com/neunhoef/cvec/releases/download/v2.5/cvec-2.5.tar.bz2

abstract: This package provides an implementation of compact vectors over finite   fields. Contrary to earlier implementations no table lookups are used   but only word-based processor arithmetic. This allows for bigger finite   fields and higher speed.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
